FROM python:latest
WORKDIR /app
RUN apt update && apt install -y \
        net-tools \
        iputils-ping \
        iproute2 \
        telnet telnetd \
        iperf \
	curl \
	iw
COPY index.html /app
CMD python -m http.server 80 
