FROM python:latest
WORKDIR /app
RUN apt update && apt install -y \
        net-tools \
        iputils-ping \
        iproute2 \
        telnet telnetd \
        iperf \
	curl \
	tcpdump \
	iw \
	iproute2 \
	net-tools \
	ethtool \
	wireless-tools 
COPY index.html /app
EXPOSE 80
CMD python -m http.server --bind 0.0.0.0 80 
