FROM python:3.8-slim-buster
WORKDIR /app
RUN apt update && apt upgrade -y && apt install -y \
        net-tools \
        iputils-ping \
        iproute2 \
        telnet telnetd \
        iperf \
	curl \
	tcpdump \
	iw \
	iproute2 \
	net-tools \
	ethtool \
	wireless-tools \
	openssh-server \
	iptables \
	openvswitch-switch

COPY index.html /app
COPY requirements.txt /app
COPY testImg.jpg /app
COPY Client.py /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 80
EXPOSE 8888


