route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1s
  receiver: scale-up
  routes:
  - match:
      service: gateway
      receiver: scale-up
      severity: major
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
receivers:
- name: 'scale-up'
  webhook_configs:
    - url: http://gateway:8080/system/alert
      send_resolved: true
      http_config:
            basic_auth:
              username: admin
              password_file: /run/secrets/basic-auth-password
